services:

  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      JWT_SECRET: college-project-secret

  employee-service:
    build:
      context: ./backend/employee-service
    container_name: employee-service
    ports:
      - "8002:8002"

  leave-service:
    build:
      context: ./backend/leave-service
    container_name: leave-service
    ports:
      - "8003:8003"

  payroll-service:
    build:
      context: ./backend/payroll-service
    container_name: payroll-service
    ports:
      - "8004:8004"

  gateway:
    build:
      context: ./gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: college-project-secret
      AUTH_URL: http://auth-service:8001
      EMPLOYEE_URL: http://employee-service:8002
      LEAVE_URL: http://leave-service:8003
      PAYROLL_URL: http://payroll-service:8004
    depends_on:
      - auth-service
      - employee-service
      - leave-service
      - payroll-service

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - gateway
