apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-service
  namespace: employee-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-service
  template:
    metadata:
      labels:
        app: leave-service
    spec:
      containers:
        - name: leave-service
          image: employee-leave-payroll-leave-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: leave-service
  namespace: employee-system
spec:
  selector:
    app: leave-service
  ports:
    - port: 8003
      targetPort: 8003
