apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-service
  namespace: employee-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-service
  template:
    metadata:
      labels:
        app: payroll-service
    spec:
      containers:
        - name: payroll-service
          image: employee-leave-payroll-payroll-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  namespace: employee-system
spec:
  selector:
    app: payroll-service
  ports:
    - port: 8004
      targetPort: 8004
